### PR TITLE
AB#2415: Don't sign & measure E2E artifacts

### PR DESCRIPTION
**Pull request by Nirusu**
### Proposed change(s)
- Build E2E CLIs as OSS
- Don't sign E2E artifacts

### CODE REVIEW

**Comment by Nirusu** [comment]
(Draft for now since we want the measurement functionality for releases, but apparently that has been extracted from E2E tests of release-ready states so far)

**Comment by Nirusu** [comment]
Should be ready for review. On demand I separated the measurement action from the E2E test.

Defaults are mostly defined in the action, not in the workflow contrary to many other workflows. I don't think most workflows trying to measure stuff would necessarily need to define all variables... but if we don't like inconsistency, I can move them to the workflow itself and pass it to the action.

**Review by malt3 — CHANGES_REQUESTED** [review]
Please also add an extra step to the release process (e2e tests are now run only for stability, measurement pipelines for GCP and Azure are run to upload measurements):

https://github.com/edgelesssys/constellation/blob/0da373e03688c85f3abb92c2fd6eac33f8a93452/.github/docs/release.md?plain=1#L44

**Comment by Nirusu** [comment]
Added.

**Review by malt3 — APPROVED** [review]
LGTM

**Pull request merged**
