### PR TITLE
helm: separate chart for CSI deployments

### PR DESCRIPTION
**Pull request by daniel-weisse**
### Context
Currently, Constellation deploys services to Kubernetes using 4 different ways:
* As part of `constellation-services` chart
* As part of `constellation-operators` chart
* Standalone helm installation for cilium
* Standalone helm installation for cert-manager

Cilium has to be installed first, since it provides networking.
The operators chart has to be deployed after cert-manager, since it requires custom resources deployed by that chart, yet cert-manager has to be deployed after the constellation-services chart, since cert-manager requires deployments from that chart to function properly.
This means we cannot make use of cert-manager in any of the sub-charts of constellation-services.

https://github.com/edgelesssys/constellation/pull/1964 introduces the installation of the CSI snapshot-controller, which requires cert-manager to set up its webhook.
This means the chart has to be installed separately from constellation-services.
This resulted in a slightly convoluted deployment and chart loading for CSI related charts.

### Proposed change(s)
- Move all CSI driver related charts into their own chart (`edgeless/csi`) to help with keeping the loading/installation process simple
- Simply helm chart installation in the bootstrapper
  - Merge `InstallConstellationServices`, `InstallChart` (previously `InstalCertManager`), and `InstallConstellationOperators` into one function.
    - They all pretty much did the same thing anyways
    - The `extraVals` parameter is an optional parameter and can be `nil`, e.g. when installing cert-manager
- Simplify helm chart loading in the CLI
  - Simplify `ccm` chart to allow for more straight-forward value setting and loading
  - Simplify most `loadXXXValues` functions by removing redundant switch-cases and conditional value setting
- Pull in the cinder CSI driver chart using the `update-csi-charts.sh` script

### Additional info
- This PR can be merged into https://github.com/edgelesssys/constellation/pull/1964
- I'm fine with not merging this (and https://github.com/edgelesssys/constellation/pull/1964) to main before the v2.9 release so we have a larger time window to test things
- I would like to add the AWS CSI chart after this PR, but am also fine with merging the AWS parts first and then rebasing my part

Test runs:
AWS: https://github.com/edgelesssys/constellation/actions/runs/5398331651
Azure: https://github.com/edgelesssys/constellation/actions/runs/5398333589
GCP: https://github.com/edgelesssys/constellation/actions/runs/5398335078

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add labels (e.g., for changelog category)
- [ ] Is PR title adequate for changelog?
- [ ] Link to Milestone

### CODE REVIEW

**Review by malt3 — APPROVED** [review]
Generally looks good to me. 

Conditions:

- as discussed, should be merged after v2.9
- I am not sure if the migration was tested explicitly. If not, please verify this works without csi volumes

**Comment by daniel-weisse** [comment]
Added an upgrade path for previously not installed charts.
Manually tested chart upgrades and seems to work fine (no PVCs are deleted on accident).
Since this PR is supposed to be merged with https://github.com/edgelesssys/constellation/pull/1964, there also shouldn't be any problems in regards to accidental CRD deletion.

Waiting for image build pipeline to finish before running the e2e upgrade test again

**Comment by daniel-weisse** [comment]
e2e upgrade test: https://github.com/edgelesssys/constellation/actions/runs/5442188243

**Comment by daniel-weisse** [comment]
Successful tests:
https://github.com/edgelesssys/constellation/actions/runs/5451667410/jobs/9918174000
https://github.com/edgelesssys/constellation/actions/runs/5451664945/jobs/9918168617

**Pull request merged**
