### PR TITLE
deps: add Kubernetes v1.27, remove Kubernetes v1.24

### PR DESCRIPTION
**Pull request by katexochen**
### Proposed change(s)

- Add Kubernetes v1.27
- Make Kubernetes v1.26 the default
- Remove Kubernetes v1.24

### Checklist

- [x] Add labels (e.g., for changelog category)

### CODE REVIEW

**Comment by katexochen** [comment]
sonobuoy full gcp https://github.com/edgelesssys/constellation/actions/runs/4822149619
sonobuoy full az https://github.com/edgelesssys/constellation/actions/runs/4822156619
sonobuoy full aws https://github.com/edgelesssys/constellation/actions/runs/4822161045

**Comment by katexochen** [comment]
Azure, 1.27: https://github.com/edgelesssys/constellation/actions/runs/4883134925
GCP, 1.27: https://github.com/edgelesssys/constellation/actions/runs/4883137035
AWS, 1.27: https://github.com/edgelesssys/constellation/actions/runs/4883140615

**Comment by 3u13r** [comment]
I think we should also bump the `ENVTEST_K8S_VERSION` in `operators/constellation-node-operator/Makefile:52` to `1.26`. `1.26.1` seems to be the newest available patch version.

**Review by 3u13r — APPROVED** [review]
LGTM

**Pull request merged**
