### PR TITLE
kubernetes: add v1.26, default to v1.25

### PR DESCRIPTION
**Pull request by katexochen**
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

### Proposed change(s)

- Add Kubernetes v1.26
- Default to v1.25

Read about major changes in the [release blog article](https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/).

### Checklist

- [ ] Update [CHANGELOG.md](https://github.com/edgelesssys/constellation/blob/main/CHANGELOG.md)
- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [x] Link to Milestone

### CODE REVIEW

**Comment by katexochen** [comment]
e2e manual run, GCP, sonobuoy quick: https://github.com/edgelesssys/constellation/actions/runs/3658897865/jobs/6184260794

**Comment by katexochen** [comment]
e2e manual run, AWS, sonobuoy quick: https://github.com/edgelesssys/constellation/actions/runs/3659581023

**Comment by katexochen** [comment]
`.../gcp-compute-persistent-disk-csi-driver/values.yaml` still contains references to the old registry, as the images aren't available at the new registry yet. See https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1093

**Review by 3u13r — APPROVED** [review]
LGTM

**Pull request merged**
