### PR TITLE
add brief instructions to AWS IAM Terraform script

### PR DESCRIPTION
**Pull request by thomasten**
Following the link from the docs to the folder, it may not be obvious for everyone what to do next. So I suggest adding these instructions.

### CODE REVIEW

**Comment by Nirusu** [comment]
If we actually promote this script, maybe we can eventually move it out of "hack/"? 

I mainly put it there because I thought it was only for development, but if that's not the case it can have a suitable directory?

**Comment by thomasten** [comment]
> If we actually promote this script, maybe we can eventually move it out of "hack/"?
> 
> I mainly put it there because I thought it was only for development, but if that's not the case it can have a suitable directory?

I don't care too much, but am open to it. What do you suggest?

**Comment by 3u13r** [comment]
Just a note: In the end the files will probably end up in `cli/internal/...' for `constellation iam create`. So we don't need to search for a fully permanent directly now. But I also see that referencing the script with the current path is not fully optimal.

**Comment by datosh** [comment]
> Just a note: In the end the files will probably end up in `cli/internal/...` for `constellation iam create`. So we don't need to search for a fully permanent directory now. But I also see that referencing the script with the current path is not fully optimal.

Docs now refer to release branch. So it should be stable for this version of the docs.

**Comment by Nirusu** [comment]
If we plan on moving the files again soon to the CLI then maybe indeed we can just keep them there for now. 

I think either way people will find them mainly through the link in the docs and not through browsing our repository directly, so it should be fine.

**Pull request merged**
