### PR TITLE
AB#2261 Add loadbalancer for control-plane recovery

### PR DESCRIPTION
**Pull request by daniel-weisse**
### Proposed change(s)

- Only start the recovery server on control-plane nodes
  - Worker nodes need a stable control-plane. If one is available no manual recovery is required
  - The server now runs on port `9999` instead of `9000`
- Create a loadbalancer for the recovery server
  - Loadbalancer has a public IP, making recovery of nodes without a public IP address (Azure) simpler

### Checklist

- [x] Update [CHANGELOG.md](https://github.com/edgelesssys/constellation/blob/main/CHANGELOG.md)
- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Link to Milestone

### CODE REVIEW

**Comment by malt3** [comment]
No super relevant, but why do we switch the port?

**Comment by daniel-weisse** [comment]
>No super relevant, but why do we switch the port?

recovery server used the same port as the bootstrapper.
We can't configure two loadbalancing rules for the same port

**Review by malt3 — APPROVED** [review]
LGTM. As a next step, we should make the endpoint optional an read it from the ID file.

**Comment by 3u13r** [comment]
> > No super relevant, but why do we switch the port?
> 
> recovery server used the same port as the bootstrapper. We can't configure two loadbalancing rules for the same port

Just thinking out loud: Can't we re-use the LB of the first port then? The healthcheck should be the same, the backend also. What is the reason we decided against that?

**Review by 3u13r — APPROVED** [review]
LGTM

**Pull request merged**
