### PR TITLE
image: upgrade to Linux 6.1.12 for Azure

### PR DESCRIPTION
**Pull request by Nirusu**
### Proposed change(s)
- Upgrade to Linux kernel 6.1.11 for Azure

This includes the important network patches for netvsc for Azure.

Guess this will be the golden kernel for a while upstream figures out what to do with the slow disk issues / MTRR story.

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [x] Add labels (e.g., for changelog category)
- [x] Link to Milestone

### CODE REVIEW

**Comment by Nirusu** [comment]
e2e test running on new image: https://github.com/edgelesssys/constellation/actions/runs/4174442891/jobs/7228019523

**Comment by Nirusu** [comment]
Actually it seems 6.1.12 was released yesterday and still doesn’t revert the MTRR commit that makes our VMs slow again.

I’ll upgrade to it later and run a test, gain.

**Comment by malt3** [comment]
Did you run another test already? The change looks good to me so feel free to merge after e2e tests pass!

**Comment by Nirusu** [comment]
Not with 6.1.12 yet, running here: https://github.com/edgelesssys/constellation/actions/runs/4183177709

Will merge it when the test succeeds then.

**Comment by Nirusu** [comment]
Tests passed, disks are fast. Let's go.

**Pull request merged**
