### PR TITLE
helm: revert parts of CoreDNS Helm chart packaging

### PR DESCRIPTION
**Pull request by burgerdev**
### Context

We are trying to move CoreDNS from a cluster addon managed by `kubeadm` to a Helm chart managed alongside the Constellation microservices.

After #3236,  upgrading a cluster reverted CoreDNS to the version installed by `kubeadm`. This required #3353 as a workaround - the cluster pretends it does not have CoreDNS to fool kubeadm, details in that PR's description.

This workaround had an unexpected consequence, though: kubeadm has a preflight check for CoreDNS, which now starts failing. Since this check is done in the upgrade-agent, which is part of the image, it does not benefit from the `--ignore`s added in #3353 and fails. Now the `kubeadm upgrade` step is never executed, which makes us miss important migrations in the worst case.

### Proposed change(s)

Extend the migration to two upgrades.

1. upgrade-agent ignores CoreDNS problems in 2.18+
2. CoreDNS is installed as Helm chart in 2.19+

### Additional info

- [AB#4627](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4627)

### Checklist

- [x] Run the E2E tests that are relevant to this PR's changes
  - ~[ ] [GCP upgrade](https://github.com/edgelesssys/constellation/actions/runs/10924437871)~
  - [x] [GCP upgrade](https://github.com/edgelesssys/constellation/actions/runs/10935780631)
  - [x] [GCP e2e](https://github.com/edgelesssys/constellation/actions/runs/10924451622)
- [x] Add labels (e.g., for changelog category)
- [x] Is PR title adequate for changelog?
- [x] Link to Milestone

### CODE REVIEW

**Review by elchead — APPROVED** [review]
we should probably add a TODO(v2.19) to the helm chart installation /  add a ticket. but I think you have this under control @burgerdev

**Comment by burgerdev** [comment]
Note to reviewers: 

There are three commits, 

* revert of #3236 
* revert of #3353 
* cherry-pick the upgrade-agent parts of #3353

Limiting the diff to the last one should be sufficient.

> we should probably add a TODO(v2.19) to the helm chart installation / add a ticket. but I think you have this under control @burgerdev

I'll add an AB ticket, thanks for the reminder.

**Review by 3u13r — APPROVED** [review]
While the upgrade test is still failing, the code itself LGTM

**Comment by burgerdev** [comment]
Interesting - failing upgrades were not even a symptom of the issue addressed here, and this branch is rebased on #3361. The failure is also during initial cluster setup at v2.17.0, which should be sufficiently tested by now. Let's see what the retry does.

**Review by msanft — APPROVED** [review]
Thanks for explaining this so thoroughly!

**Pull request merged**
