### PR TITLE
Update go-tpm-tools to fix AWS PCR selection

### PR DESCRIPTION
**Pull request by daniel-weisse**
### Proposed change(s)

- The relevant fix: https://github.com/daniel-weisse/go-tpm-tools/commit/f2255501dfc41093191240c9f64778ed5fa03ff2

### CODE REVIEW

**Comment by daniel-weisse** [comment]
Ignored the leaking glog Go routines in our unit tests.
Also had to upgrade to Go 1.19.
We were already using 1.19 to build our binaries, so this should not make much of a difference, now its just present in our go.mod file.

**Comment by malt3** [comment]
> Also had to upgrade to Go 1.19.

Can you explain why this is necessary?

**Comment by daniel-weisse** [comment]
Required by indirect dependency on `github.com/google/go-sev-guest`

**Comment by katexochen** [comment]
If you want to make a Go version update, please 1) do it on a separate branch and 2) follow the common practice for upgrading Go versions: read the change log, run go fix, include improvements etc... 
If you like, I can do the upgrade, too.

**Comment by daniel-weisse** [comment]
>If you like, I can do the upgrade, too.

Yes, please go ahead

**Review by malt3 — APPROVED** [review]
LGTM

**Pull request merged**
