### PR TITLE
ci: fix scorecard/pinned-dependencies findings

### PR DESCRIPTION
**Pull request by datosh**
Signed-off-by: Fabian Kammel <fk@edgeless.systems>

### Proposed change(s)

Fix findings reported by scorecard:

```
scorecard --repo=https://github.com/edgelesssys/constellation --show-details --checks=Pinned-Dependencies
Starting [Pinned-Dependencies]
Finished [Pinned-Dependencies]

RESULTS
-------
Aggregate score: 7.0 / 10

Check scores:
|--------|---------------------|--------------------------------|--------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| SCORE  |        NAME         |             REASON             |                                       DETAILS                                        |                           DOCUMENTATION/REMEDIATION                            |
|--------|---------------------|--------------------------------|--------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| 7 / 10 | Pinned-Dependencies | dependency not pinned by hash  | Warn: containerImage not pinned by hash: hack/azure-snp-report-verify/Dockerfile:1:  | https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies |
|        |                     | detected -- score normalized   | pin your Docker image by updating ubuntu:20.04 to                                    |                                                                                |
|        |                     | to 7                           | ubuntu:20.04@sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb |                                                                                |
|        |                     |                                | Warn: containerImage not pinned by hash: hack/azure-snp-report-verify/Dockerfile:13: |                                                                                |
|        |                     |                                | pin your Docker image by updating ubuntu:20.04 to                                    |                                                                                |
|        |                     |                                | ubuntu:20.04@sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb |                                                                                |
|        |                     |                                | Warn: pipCommand not pinned by hash: .github/workflows/build-os-image.yml:550        |                                                                                |
|        |                     |                                | Warn: goCommand not pinned by hash: .github/workflows/check-licenses.yml:33 Warn:    |                                                                                |
|        |                     |                                | npmCommand not pinned by hash: .github/workflows/release.yml:80 Warn: goCommand not  |                                                                                |
|        |                     |                                | pinned by hash: .github/workflows/test-actionlint.yml:38 Warn: goCommand not pinned  |                                                                                |
|        |                     |                                | by hash: .github/workflows/test-go-generate.yml:35 Warn: goCommand not pinned by     |                                                                                |
|        |                     |                                | hash: .github/workflows/test-govulncheck.yml:49 Info: GitHub-owned GitHubActions     |                                                                                |
|        |                     |                                | are pinned Info: Third-party GitHubActions are pinned Info: no insecure (not pinned  |                                                                                |
|        |                     |                                | by hash) dependency downloads found in Dockerfiles Info: no insecure (not pinned by  |                                                                                |
|        |                     |                                | hash) dependency downloads found in shell scripts                                    |                                                                                |
|--------|---------------------|--------------------------------|--------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
```

### Checklist

- [x] ~Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)~
- [x] Add labels (e.g., for changelog category)
- [x] Link to Milestone

### CODE REVIEW

**Review by malt3 — APPROVED** [review]

**Comment by datosh** [comment]
Based on feedback by @katexochen I have refactored the installation of `lief` into a `requirements.txt` that should be picked up by renovate for updates. Also pinned our other `requirements.txt`s by hash.

**Comment by katexochen** [comment]
Do you want to add the checking workflow in this PR?

**Comment by datosh** [comment]
> Do you want to add the checking workflow in this PR?

I added an extra PR #986 for this, but I will wait merging this until the checks are merged

**Comment by datosh** [comment]
Rebased this onto main. Do you want to have another look @katexochen or is this good to get merged?

**Review by katexochen — APPROVED** [review]

**Pull request merged**
