### PR TITLE
ci: Upload e2e terraform state as artifact

### PR DESCRIPTION
**Pull request by miampf**
### Context

Upload the terraform state of E2E tests (and other actions that use `constellation_create/action.yml`) as a github artifact. This allows to manually clean up resources and makes automation later on easy.

### Proposed change(s)

- add a step to upload `constellation-terraform` and `constellation-iam-terraform` in `.github/actions/constellation_create/action.yml`

### Checklist

- [x] Add labels (e.g., for changelog category)
- [x] Link to Milestone

### CODE REVIEW

**Comment by miampf** [comment]
E2E Test: https://github.com/edgelesssys/constellation/actions/runs/7641854082

**Review by katexochen — CHANGES_REQUESTED** [review]
We should remove the `.terraform/` directories (which contain the provider binaries) as well as the `plan.zip` from `constellation-terraform/` to safe some space.

**Comment by miampf** [comment]
The glob patterns need to be matched in a previous step and written to a variable. This variable can then be used in the artifact upload step.

**Comment by miampf** [comment]
> Seems to work as expected 👍 https://github.com/edgelesssys/constellation/actions/runs/7711725301

Unfortunately it does not work as expected. I would expect a `constellation-terraform` and a `constellation-iam-terraform` folder, each with their own states. I will look into a fix today.

**Comment by miampf** [comment]
Everything seems to work as expected now: https://github.com/edgelesssys/constellation/actions/runs/7727511372

**Pull request merged**
