### PR TITLE
deps: update AWS cloud controller manager

### PR DESCRIPTION
**Pull request by katexochen**
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

### Proposed change(s)

- Picked the minor ver update for 1.24 from #799, which is still blocked
- Updated major ver for k8s v1.26 to ccm v1.26.0

### Checklist

- [x] Add labels (e.g., for changelog category)

### CODE REVIEW

**Review by derpsteb — APPROVED** [review]
Nodes seem to start fine. [e2e manual sonobuoy quick, 2+3 nodes, 1.25](https://github.com/edgelesssys/constellation/actions/runs/3821278444/jobs/6500732826)

**Comment by katexochen** [comment]
@derpsteb the v1.26 ccm is only used with k8s v1.26 :wink:

**Review by 3u13r — APPROVED** [review]
LGTM

**Comment by derpsteb** [comment]
Whoops.
Anyway, here is the updated run: https://github.com/edgelesssys/constellation/actions/runs/3828857680

**Pull request merged**
