### PR TITLE
ci: add force flag to remaining constellation cmds

### PR DESCRIPTION
**Pull request by derpsteb**
### Proposed change(s)

- In the CI most configs use prerelease images. Config validation prevents this. Therefore we need to use the force flag for now.
- Discussion on UX of the flag is ongoing. Adding this to fix the pipeline for the time being.

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [x] Add labels (e.g., for changelog category)
- [x] Link to Milestone

### CODE REVIEW

**Comment by katexochen** [comment]
e2e recover, 1.25, Azure: https://github.com/edgelesssys/constellation/actions/runs/4174272246

**Comment by katexochen** [comment]
e2e verify, 1.25, GCP: https://github.com/edgelesssys/constellation/actions/runs/4174282713

**Comment by katexochen** [comment]
The GCP run failed, error:
```
Warning: Failed to validate attestation document: untrusted PCR value at PCR index 10
```

**Comment by derpsteb** [comment]
Perfect timing.

**Comment by Nirusu** [comment]
PCR 10 is one of the unstable PCRs. This was attempted to be fixed with #1152 and indeed it is supposed to be warnOnly:

```bash
Updating 10 to { "warnOnly": true, "expected": "7f96fbc55e1d2a0de46e5d44658c06ef102d1198703efa69f2ea6b5aa1c9a176" }
 
[...]

10:
        warnOnly: false
        expected: 7f96fbc55e1d2a0de46e5d44658c06ef102d1198703efa69f2ea6b5aa1c9a176
```

But eventually something sets it back to false? Though maybe we should upgrade the new expected value or kick this out in the first place if we cannot pin this reliably anyway.

**Comment by Nirusu** [comment]
Apparently we already kicked this out for Azure and AWS. So let's throw out PCR 10 for GCP, too.

**Comment by derpsteb** [comment]
With `warnOnly`-overwrite removed: [GCP, 1.25.6, 2+3, verify](https://github.com/edgelesssys/constellation/actions/runs/4181382709)

**Review by katexochen — APPROVED** [review]
lgtm :dodo:

**Pull request merged**
