### PR TITLE
bazel: identical containers regardless of platform

### PR DESCRIPTION
**Pull request by malt3**
### Proposed change(s)

- bazel: identical containers regardless of platform
- automated test to find sources of non-deterministic / platform specific behavior

### Additional info

I found three sources of differences in the container images so far:

- https://github.com/bazelbuild/rules_go/issues/3581
  - TL;DR: proto rules introduce a path that differs between platforms and is embedded in any go binary that embeds the proto library
- https://github.com/bazel-contrib/rules_oci/pull/172
  - TL;DR: When using `oci_image` with a base, it's UB to also define `os` and `architecture`
- https://github.com/rmohr/bazeldnf/issues/58
  - TL;DR: bazeldnf `rpm2tar` produces non-deterministic tar files when symlinks are used
- unstripped go binaries contain debug symbols related to the platform (this seems to start with the go sdk itself)
  - TL;DR: use a version of rules_go that [supports stripping](https://github.com/bazelbuild/rules_go/pull/3527)

### How to test

As a reviewer, please comment with a list of the cli hashes you saw.
For the CLI to be built reproducible, you need to unset `build --container_prefix=FOO` in your .bazeloverwriterc.
For this, please report: The git commit you are on, if the workspace is clean (git status), the host platform (built on Ubuntu 22.04  / amd64 | built on macOS with m1), the bazel target platform (i.e. `bazel build [...] --platforms=<TARGET_PLATFORM>`), the build target with platform (`cli_enterprise_linux_amd64`).

- `bazel test //bazel/release/artifacts:artifacts_test` (Should be green, if you remove the fix for bazeldnf, it should be red)
- build the cli multiple times while specifying different platform, see if the same binary is produced:
  - `bazel build //cli:cli_enterprise_linux_amd64 && sha256sum bazel-bin/cli/cli_enterprise_linux_amd64`
  - `bazel build //cli:cli_enterprise_linux_amd64  --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 && sha256sum bazel-bin/cli/cli_enterprise_linux_amd64`
  - `bazel build //cli:cli_enterprise_linux_amd64  --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64 && sha256sum bazel-bin/cli/cli_enterprise_linux_amd64`
  - `bazel build //cli:cli_enterprise_linux_amd64  --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 && sha256sum bazel-bin/cli/cli_enterprise_linux_amd64`
  - `bazel build //cli:cli_enterprise_linux_amd64  --platforms=@io_bazel_rules_go//go/toolchain:darwin_arm64 && sha256sum bazel-bin/cli/cli_enterprise_linux_amd64`
  - `bazel build //bazel/release:container_sums && sha256sum bazel-bin/bazel/release/container_sums.sha256`
  - `bazel build //bazel/release:container_sums  --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 && sha256sum bazel-bin/bazel/release/container_sums.sha256`
  - `bazel build //bazel/release:container_sums  --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64 && sha256sum bazel-bin/bazel/release/container_sums.sha256`
  - `bazel build //bazel/release:container_sums  --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 && sha256sum bazel-bin/bazel/release/container_sums.sha256`
  - `bazel build //bazel/release:container_sums  --platforms=@io_bazel_rules_go//go/toolchain:darwin_arm64 && sha256sum bazel-bin/bazel/release/container_sums.sha256`
- build the cli on different host systems (different linux distros, different architectures, macOS) and see if the same binary is produced when building `//cli:cli_enterprise_linux_amd64` (or any of the other CLI targets that have a hardcoded platform `bazel query //cli:all`)

### Build table

| Commit                                   | Host                 | Bazel platform | Target                     | Hash                                                             |
|------------------------------------------|----------------------|----------------|----------------------------|------------------------------------------------------------------|
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | host (empty)   | cli_enterprise_linux_amd64 | 3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | linux_amd64    | cli_enterprise_linux_amd64 | 3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | linux_arm64    | cli_enterprise_linux_amd64 | 3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | darwin_amd64   | cli_enterprise_linux_amd64 | 3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | darwin_arm64   | cli_enterprise_linux_amd64 | 3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | host (empty)   | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | linux_amd64    | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | linux_arm64    | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | darwin_amd64   | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Ubuntu 22.04 / amd64 | darwin_arm64   | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add labels (e.g., for changelog category)
- [ ] Link to Milestone
- [ ] Wait for fix of https://github.com/rmohr/bazeldnf/issues/58 to be merged

### CODE REVIEW

**Comment by katexochen** [comment]
Verified all hashes on NixOS :snowflake: :heavy_check_mark:

**Comment by daniel-weisse** [comment]
workspace: clean
```sh
$ bazel test //bazel/release/artifacts:artifacts_test
//bazel/release/artifacts:artifacts_test                                 PASSED in 1.5s
```

Commit | Host | Bazel platform | Target | Hash
-- | -- | -- | -- | --
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | host (empty) | cli_enterprise_linux_amd64 | 633e7aad164fae9c2df683f828bd6dcfa6975541c8c7ca9bdb7a18f1ffb5ea11
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | linux_amd64 | cli_enterprise_linux_amd64 | 633e7aad164fae9c2df683f828bd6dcfa6975541c8c7ca9bdb7a18f1ffb5ea11
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | linux_arm64 | cli_enterprise_linux_amd64 | 633e7aad164fae9c2df683f828bd6dcfa6975541c8c7ca9bdb7a18f1ffb5ea11
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | darwin_amd64 | cli_enterprise_linux_amd64 | 633e7aad164fae9c2df683f828bd6dcfa6975541c8c7ca9bdb7a18f1ffb5ea11
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | darwin_arm64 | cli_enterprise_linux_amd64 | 633e7aad164fae9c2df683f828bd6dcfa6975541c8c7ca9bdb7a18f1ffb5ea11
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | host (empty) | container_sums | 05b96981229e76987e2eda633a4e195555625fd6644a005b825ea3ebea7a41b7
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | linux_amd64 | container_sums | 05b96981229e76987e2eda633a4e195555625fd6644a005b825ea3ebea7a41b7
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | linux_arm64 | container_sums | 05b96981229e76987e2eda633a4e195555625fd6644a005b825ea3ebea7a41b7
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | darwin_amd64 | container_sums | 05b96981229e76987e2eda633a4e195555625fd6644a005b825ea3ebea7a41b7
275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Fedora 37 (Workstation) / amd64 | darwin_arm64 | container_sums | 05b96981229e76987e2eda633a4e195555625fd6644a005b825ea3ebea7a41b7

**Comment by malt3** [comment]
@daniel-weisse can you retry without `build --container_prefix=FOO` in your bazelrc?

**Comment by daniel-weisse** [comment]
Build hashes when unsetting the container-prefix build flag:

CLI: `3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706`
Containers: `dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec`

**Review by daniel-weisse — APPROVED** [review]

**Comment by msanft** [comment]
Git Status:
```
modified:   .bazelversion
```
(Needed to switch to Bazel 6.2.0 as this is the only version I have available ootb, can test with 6.2.1 tomorrow)

Artifact Test:
```
//bazel/release/artifacts:artifacts_test                                 PASSED in 0.9s
```


| Commit                                   | Host                 | Bazel platform | Target                     | Hash                                                             |
|------------------------------------------|----------------------|----------------|----------------------------|------------------------------------------------------------------|
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | host (empty) | cli_enterprise_linux_amd64 | b8dd472a371f4ca394751dc8e94cd96bf76d9c761d41a0d6f9e91974909013c3 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | linux_amd64 | cli_enterprise_linux_amd64 | b8dd472a371f4ca394751dc8e94cd96bf76d9c761d41a0d6f9e91974909013c3 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | linux_arm64 | cli_enterprise_linux_amd64 | b8dd472a371f4ca394751dc8e94cd96bf76d9c761d41a0d6f9e91974909013c3 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | darwin_amd64 | cli_enterprise_linux_amd64 | b8dd472a371f4ca394751dc8e94cd96bf76d9c761d41a0d6f9e91974909013c3 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | darwin_arm64 | cli_enterprise_linux_amd64 | b8dd472a371f4ca394751dc8e94cd96bf76d9c761d41a0d6f9e91974909013c3 |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | host (empty) | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | linux_amd64 | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | linux_arm64 | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | darwin_amd64 | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |
| 275ad5eaae0fb7f094e8e6055af9ed1682754b02 | Darwin 22.5.0 / aarch64 | darwin_arm64 | container_sums             | dc695d855b6510025b0fb82fa2843adfddaaedf3f3f94052148923715774f9ec |

**Comment by derpsteb** [comment]
Could reproduce all hashes on Ubuntu 22.04, x86. But only after Malte figured out that I needed to remove `build --container_prefix=ghcr.io/derpsteb/constellation` from my `.bazeloverwriterc`. Otherwise the prefix ends up in the CLI.

**Comment by msanft** [comment]
Update:

With Malte's help and a clean git working tree, I was able to reproduce the CLI hash too:
`3881c8d15a73b77676d84851e08d85b92eebe76d8927b7c7a549812709240706`

-> ✅ from aarch64 Darwin

**Pull request merged**
