### PR TITLE
github: add AB ticket link to PR template

### PR DESCRIPTION
**Pull request by msanft**
### Context

Mentioning Azure DevOps tickets in GitHub PRs links the ticket to the PR in Azure DevOps. This helps at backlog refinements and general mapping of tickets to PRs.

### Proposed change(s)

- Add a link to an AB ticket in the GitHub pull request template.

### Checklist

- [x] Add labels (e.g., for changelog category)
- [x] Is PR title adequate for changelog?
- [x] Link to Milestone

### CODE REVIEW

**Review by elchead — CHANGES_REQUESTED** [review]
I like to put in the reminder, but I think that the link is not very helpful.
You can simply type AB#$NBR to add the link.
My suggestion would be to make additional info not optional and add AB# in the template

**Comment by msanft** [comment]
> You can simply type AB#$NBR to add the link. 

What do you mean by that?

> My suggestion would be to make additional info not optional and add AB# in the template

Agreed.

**Comment by elchead** [comment]
You can ofc also provide the link but I think the template should not "force" using a link (i.e. let's just put AB# and let the creator decide how he links)

**Comment by msanft** [comment]
> You can ofc also provide the link but I think the template should not "force" using a link (i.e. let's just put AB# and let the creator decide how he links)

I don't really see the point for only putting the number. When you paste the number, you could also just paste it again in the link. What's your point against putting the link exactly?

**Comment by elchead** [comment]
> > You can ofc also provide the link but I think the template should not "force" using a link (i.e. let's just put AB# and let the creator decide how he links)
> 
> I don't really see the point for only putting the number. When you paste the number, you could also just paste it again in the link. What's your point against putting the link exactly?

I will just always have to delete it since I think its easier to memorize a number than copying the link and also adjusting the link name. But it's ok.

**Review by elchead — APPROVED** [review]

**Comment by msanft** [comment]
> I will just always have to delete it since I think its easier to memorize a number than copying the link and also adjusting the link name. But it's ok.

Just to clarify the misunderstanding (at least I think it is one) here; My idea was that one only memorizes the number and replaces both `1234` with the memorized number (the one in the link name as well as the one in the link). This way, both name and link should be correct

**Comment by elchead** [comment]
FYI putting AB#number already creates a link by the github bot ;) @msanft

**Pull request merged**
