### PR TITLE
deps: update replaced Constellation version

### PR DESCRIPTION
**Pull request by katexochen**
### Proposed change(s)

- Build currently fails after sbom analysis: https://github.com/edgelesssys/constellation/actions/runs/4231365542/jobs/7349798178#step:4:780

### Checklist

- [x] Add labels (e.g., for changelog category)

### CODE REVIEW

**Comment by katexochen** [comment]
build constellation node operator: https://github.com/edgelesssys/constellation/actions/runs/4231708888

**Comment by katexochen** [comment]
doesn't seem to help, we'll need to ignore this

**Comment by malt3** [comment]
> doesn't seem to help, we'll need to ignore this

@katexochen https://github.com/anchore/grype#specifying-matches-to-ignore

**Comment by katexochen** [comment]
Closed by #1248

**Pull request closed without merging**
