### PR TITLE
cli: move Talos YAML dependencies into its own smaller package

### PR DESCRIPTION
**Pull request by Nirusu**
### Proposed change(s)
- Move Talos' YAML encoder & docgen to: https://github.com/edgelesssys/annotated-yaml

### CODE REVIEW

**Comment by datosh** [comment]
I'm a bit suprised there are basically no changes in our `go.sum`, since it sounded like we are pulling in a lot of things via this `talos/pkg/machinery` dependency. Not sure if there is any benefit now, if we need to maintain our own "fork" instead of letting Renovate bump the version every now and then.

**Comment by Nirusu** [comment]
There's not that many dependencies:
https://github.com/siderolabs/talos/blob/main/pkg/machinery/go.mod

**Comment by Nirusu** [comment]
Test is failing because I initially tagged v1.0.0 but switched to v0.1.0. I will also change and replace the v0.1.0 a few times, so I hope tests will pass in later when the Go proxy empties its cache.

**Comment by Nirusu** [comment]
But maybe we should decide first whether to go through with this or not, if it doesn't serve any benefit 😄

**Comment by Nirusu** [comment]
From what I can tell Go really only imports the encoder package, not the rest of the machinery package.

In this case I think this can definitely be closed for now. In case Talos breaks something / adds more dependencies, we can revisit this again.

**Pull request closed without merging**
