### PR TITLE
versions: default to k8s v1.29, support k8s v1.30, EOL v1.27

### PR DESCRIPTION
**Pull request by burgerdev**
### Context

Kubernetes released v1.30 on 2024-04-17.

### Proposed change(s)

- Remove support for k8s v1.27.
- Add support for k8s v1.30.
- Upgrade k8s components and CCM images to latest patch versions.

### Additional info

- [AB#4073](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4073)

### Checklist
- [x] Run the E2E tests that are relevant to this PR's changes
  - [x] [Azure @ v1.30](https://github.com/edgelesssys/constellation/actions/runs/9578948740)
  - [x] ~[GCP @ v1.30](https://github.com/edgelesssys/constellation/actions/runs/9578953671)~
  - [x] [AWS @ v1.30](https://github.com/edgelesssys/constellation/actions/runs/9578967898) 
  - [x] [Azure @ v1.29](https://github.com/edgelesssys/constellation/actions/runs/9580008285)
  - [x] ~[GCP @ v1.29](https://github.com/edgelesssys/constellation/actions/runs/9580013137)~
  - [x] [AWS @ v1.29](https://github.com/edgelesssys/constellation/actions/runs/9580016093)
  - [x] [Upgrade from Azure v2.16.4](https://github.com/edgelesssys/constellation/actions/runs/9581508507)
  - [x] [Upgrade from GCP v2.16.4](https://github.com/edgelesssys/constellation/actions/runs/9581515850)
  - [x] [Upgrade from AWS v2.16.4](https://github.com/edgelesssys/constellation/actions/runs/9581520185)
  - [x] GCP with Edgeless CCM:
    - [x] 1.28 https://github.com/edgelesssys/constellation/actions/runs/9583900227
    - [x] 1.29 https://github.com/edgelesssys/constellation/actions/runs/9583904569
    - [x] 1.30 https://github.com/edgelesssys/constellation/actions/runs/9583907513
- [x] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [x] Add labels (e.g., for changelog category)
- [x] Is PR title adequate for changelog?
- [x] Link to Milestone

### CODE REVIEW

**Review by daniel-weisse — COMMENTED** [review]
Also need to update the default K8s version used in our e2e tests

**Review by daniel-weisse — APPROVED** [review]
lgtm when test pass

**Review by msanft — CHANGES_REQUESTED** [review]
If we EOL 1.27, we should also remove it from the release and weekly test matrix and run 1.30 instead, right?

**Comment by burgerdev** [comment]
Good catch, fixed in [eec9ccc](https://github.com/edgelesssys/constellation/pull/3173/commits/eec9ccc5b225b4847b17c0cf1e11a488b4c89a89). I triggered a couple of upgrade tests, but won't add any more unless somebody insists.

**Review by msanft — APPROVED** [review]

**Pull request merged**
