### PR TITLE
hack: move terraform readmes into cli

### PR DESCRIPTION
**Pull request by katexochen**
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

### Proposed change(s)

- IAM creation is now part of the official CLI. The documentation in hack is replaced by the official docs.
- Moving developer documentation about iamlive to the devdoc directory.

### Checklist

- [x] Add labels (e.g., for changelog category)

### CODE REVIEW

**Comment by thomasten** [comment]
Note that there's a reference from the docs to the AWS IAM Readme:
https://github.com/edgelesssys/constellation/blob/49534d463d912f0c28b4a27efaaed7de3f761cc3/docs/docs/workflows/config.md?plain=1#L221-L231

**Comment by katexochen** [comment]
> Note that there's a reference from the docs to the AWS IAM Readme

Hm.. should we delete the link or keep the readmes but move them back to the terraform code?

**Comment by thomasten** [comment]
> > Note that there's a reference from the docs to the AWS IAM Readme
> 
> Hm.. should we delete the link or keep the readmes but move them back to the terraform code?

Oh, I haven't noticed yet that the terraform code has been moved.

I don't have a strong opinion. For now, the links still work because they are pinned to v2.2. I guess #724 will change that part of the docs anyway and make that readme file finally obsolete? Then I would be fine with either your suggestion or keep your PR as is.

**Comment by katexochen** [comment]
I'll move it back to the terraform code, might be a good starter for documenting the thing.

**Comment by katexochen** [comment]
I didn't update the links, as there is no newer stable link to update to. In v2.3.0 the readme is in another folder as the terraform. Imo we should rethink how we can update references like this in the docs, or if we want them at all.

**Review by thomasten — APPROVED** [review]

**Pull request merged**
